name:                udp-server
version:             0.0.1.0
github:              "nshimaza/udp-server"
license:             MIT
author:              "Naoto Shimazaki"
maintainer:          "Naoto.Shimazaki@gmail.com"
copyright:           "2019-2020 Naoto Shimazaki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nshimaza/udp-server#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- data-default-class
- network
- unliftio

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - thread-supervisor >= 0.2

tests:
  udp-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wno-incomplete-uni-patterns
    - -Wno-missing-signatures
    - -Wno-type-defaults
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
      - hspec-discover
    dependencies:
    - udp-server
    - QuickCheck
    - quickcheck-instances
    - hspec
