name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: actions/setup-haskell@v1.1.2
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', '**/*.yaml', '**/stack.yaml.lock') }}

    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      run: stack test
